# Generated by Django 4.2.16 on 2024-11-02 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100, verbose_name="企業名")),
                ("buy_price", models.BigIntegerField(verbose_name="購入金額")),
                ("buy_shares", models.BigIntegerField(verbose_name="株数")),
                ("sell_price", models.BigIntegerField(verbose_name="売却金額")),
                ("sell_shares", models.BigIntegerField(verbose_name="売却量")),
                ("buy_day", models.DateField(verbose_name="購入日")),
                ("sell_day", models.DateField(verbose_name="売却日")),
            ],
        ),
    ]
