# Generated by Django 4.2.16 on 2024-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_log_page_buy_reason"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
        migrations.AddField(
            model_name="page",
            name="benefit",
            field=models.BigIntegerField(default=0, verbose_name="損益"),
        ),
        migrations.AddField(
            model_name="page",
            name="sell_day",
            field=models.DateField(default="2000-01-01", verbose_name="売却日"),
        ),
        migrations.AddField(
            model_name="page",
            name="sell_price",
            field=models.BigIntegerField(default=0, verbose_name="売却金額"),
        ),
        migrations.AddField(
            model_name="page",
            name="sell_reason",
            field=models.TextField(default="未記入", max_length=1000, verbose_name="売却理由"),
        ),
        migrations.AddField(
            model_name="page",
            name="sell_shares",
            field=models.BigIntegerField(default=0, verbose_name="売却量"),
        ),
        migrations.AlterField(
            model_name="page",
            name="buy_reason",
            field=models.TextField(max_length=1000, verbose_name="購入理由"),
        ),
    ]
