# Generated by Django 4.2.16 on 2024-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0003_delete_log_page_benefit_page_sell_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_sell",
            field=models.BooleanField(default=False, verbose_name="売却判定"),
        ),
    ]
